/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirliners;

import Business.Airliner;
import Business.Flight;
import Business.TravelAgency;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author vikram
 */
public class CreateNewAirlinerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateNewAirlinerJPanel
     */
    
    //AirlinerDirectory airlinerDirectory;
    JPanel cardSequenceJPanel;
    TravelAgency travelAgency;
    Airliner airline;


    CreateNewAirlinerJPanel(JPanel cardSequenceJPanel, TravelAgency travelAgency) {
        initComponents();
        this.cardSequenceJPanel = cardSequenceJPanel; 
        this.travelAgency = travelAgency;
        
           Airliner result = travelAgency.getAirlinerDirectory().searchAirliner(txtAirlinerName.getText());
        /*if (result == null) {
           txtNoOfFlights.setText(""); 
            
        }
        else{
            
           txtNoOfFlights.setText(String.valueOf(result.getFlightDir().getFlightList().size()));
            
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAirlinerName = new javax.swing.JTextField();
        txtAirlinerId = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        txtAirlinerAddress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnAddPlane = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create Airliner");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 800, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Airliner Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 110, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Airliner ID");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 90, 30));

        txtAirlinerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAirlinerNameActionPerformed(evt);
            }
        });
        add(txtAirlinerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 200, 30));
        add(txtAirlinerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 200, 30));

        btnCreate.setText("Create Airliner");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 200, 40));

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 160, 30));
        add(txtAirlinerAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 200, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Address");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 90, 20));

        btnAddPlane.setText("Add Plane >>");
        btnAddPlane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPlaneActionPerformed(evt);
            }
        });
        add(btnAddPlane, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, 160, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        String airlinerName = txtAirlinerName.getText();
        String airlinerId = txtAirlinerId.getText();
        String address = txtAirlinerAddress.getText();
        for(Airliner a:travelAgency.getAirlinerDirectory().getAirliners()){
            if((a.getAirlinerName().equals(airlinerName))||(a.getAirlinerId().equals(airlinerId))){
                  JOptionPane.showMessageDialog(null, "Airliner already exists");
            return;
                
            }
        }
        
        if (airlinerName.equals("") || airlinerId.equals("") || address.equals("") ) {
            JOptionPane.showMessageDialog(null, "All fields are mandatory");
            return;
        }
        else{
            airline = travelAgency.getAirlinerDirectory().addAirliner();
            airline.setAirlinerName(airlinerName);
            airline.setAirlinerId(airlinerId);
            airline.setAirlinerAddress(address);
            //airline.setNoOfFlights(noOfFlights);
            
            JOptionPane.showMessageDialog(null, "Airliner created successfully.! You can now add planes to this airliner");
        }        
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        cardSequenceJPanel.remove(this);
        Component[] componentArray = cardSequenceJPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageAirlinersJPanel manageAccountJPanel = (ManageAirlinersJPanel) component;
        manageAccountJPanel.populateTable();
        CardLayout layout = (CardLayout) cardSequenceJPanel.getLayout();
        layout.previous(cardSequenceJPanel);
    }//GEN-LAST:event_btnBackActionPerformed
    
    private void btnAddPlaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPlaneActionPerformed
        // TODO add your handling code here:
        
        if (airline == null) {
            JOptionPane.showMessageDialog(null, "Save the airliner before adding flights");
            return;}else{
        CreateNewPlaneJPanel panel = new CreateNewPlaneJPanel(cardSequenceJPanel,airline,travelAgency);
        cardSequenceJPanel.add("CreateNewPlaneJPanel", panel);
        CardLayout layout = (CardLayout) cardSequenceJPanel.getLayout();
        layout.next(cardSequenceJPanel);}
    }//GEN-LAST:event_btnAddPlaneActionPerformed

    private void txtAirlinerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAirlinerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAirlinerNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPlane;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtAirlinerAddress;
    private javax.swing.JTextField txtAirlinerId;
    private javax.swing.JTextField txtAirlinerName;
    // End of variables declaration//GEN-END:variables
}
